development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: malimar_dev
  port:    8889
  username: root
  password: root
  host: localhost
  socket: /Applications/MAMP/tmp/mysql/mysql.sock
  pool: 50

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: malimar_test
  port:    8889
  username: root
  password: root
  host: localhost
  socket: /Applications/MAMP/tmp/mysql/mysql.sock
  pool: 50

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: malimar_prod
  port:    3306
  username: malimar_app
  password: C98CBB28D13D8BAF
  host: 104.131.205.115
  socket: /var/run/mysqld/mysqld.sock
  pool: 50
