development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: malimar_dev
  port:    8889 
  username: root
  password: root
  host: localhost
  socket: /Applications/MAMP/tmp/mysql/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: malimar_test
  port:    8889 
  username: root
  password: root
  host: localhost
  socket: /Applications/MAMP/tmp/mysql/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: malimar_prod
  port:    3306 
  username: root
  password: rails123
  host: localhost
  socket: /var/run/mysqld/mysqld.sock